basic:
  seed: 202205
  device: 'gpu' # cpu / gpu
  save:
    period: 20 # every 1 epoch save
    best: True # save the best score

dataset:
  name: 'PlantSeedlings'
  path: '/home/whlzy90/data/plant_seedlings'
  rate: 0.9
  train:
    Resize: [224, 224]
    #RandomCrop: [224, 224]
    RandomHorizontalFlip: True
    RandomVerticalFlip: True
    #ColorJitter: [0.2, 0.2, 0.2, 0.2]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  test:
    Resize: [224, 224]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]



model:
  # ResNet18
  block: BasicBlock
  layers: [2, 2, 2, 2]
  num_classes: 12
  # ResNet50
  # block: Bottleneck
  # layers: [3, 4, 6, 3]
  # num_classes: 12

train:
  max_epoch: 100
  batch_size: 128
  lr: 2e-4
  num_workers: 4
  optimizer:
    # type: 'adamw' # sgd / 'adamw'
    # beta1: 0.9
    # beta2: 0.999

    type: 'sgd'
    momentum: 0.99
    weight_decay: 1e-4
  schedule:
    type: 'Cosine' # Cosine / None / MultiStep
    minlr: 0
    period: 100
    # warmup: 'linear'
    # warmup_iters: 1 # 1 epoch
    # warmup_ratio: 1e-4

    # type: 'MultiStep' # Cosine / None / MultiStep
    # milestones: [5, 10]
    # gamma: 0.5