basic:
  seed: 202205
  device: 'gpu' # cpu / gpu
  save:
    period: 1 # every 1 epoch save
    best: True # save the best score

dataset:
  name: 'PlantSeedlings'
  path: './datasets/Plant_Seedlings'
  rate: 0.8  # train:val = 4:1
  num_classes: 12
  train:
    Resize: [224, 224]
    RandomHorizontalFlip: 90
    RandomVerticalFlip:
    RandomCrop: 224
    RandomRotation: 90
#     ColorJitter:
    HorizontalFlip:
    VerticalFlip:
    Normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  test:
    Resize: [224, 224]
    Normalize:
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 0.5, 0.5, 0.5 ]


model:
  act: 'Hardswish' # Hardswish / ReLU
  net_dim: [2, 2, 2, 2]

train:
  max_epoch: 50
  batch_size: 64
  lr: 1e-3
  optimizer:
    type: 'adamw' # sgd / 'adamw'
    beta1: 0.9
    beta2: 0.999
    # type: 'sgd'
    # momentum: 0.99
    # weight_decay: 1e-4
  schedule:
    type: 'Cosine' # Cosine / None / MultiStep
    minlr: 0
    period: 10
    warmup: 'linear'
    warmup_iters: 1 # 1 epoch
    warmup_ratio: 1e-4

    # type: 'MultiStep' # Cosine / None / MultiStep
    # milestones: [5, 10]
    # gamma: 0.5