basic:
  seed: 202205
  device: 'gpu' # cpu / gpu
  save:
    period: 1 # every 1 epoch save
    best: True # save the best score

dataset:
  name: 'PlantSeedlings'
  path: '/home/whlzy90/data/plant_seedlings'
  rate: 0.9
  train:
    Resize: [224, 224]
    #RandomCrop: [224, 224]
    RandomHorizontalFlip: True
    RandomVerticalFlip: True
    ColorJitter: [0.2, 0.2, 0.2, 0.2]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  test:
    Resize: [224, 224]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]


model:
  cfg: [ 64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M' ]
#  {'A': [ 64, 'M', 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M' ],  # 11 layers
#  'B': [ 64, 64, 'M', 128, 128, 'M', 256, 256, 'M', 512, 512, 'M', 512, 512, 'M' ],  # 13 layers
#  'D': [ 64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M' ],  # 16 layers
#  'E': [ 64, 64, 'M', 128, 128, 'M', 256, 256, 256, 256, 'M', 512, 512, 512, 512, 'M', 512, 512, 512, 512, 'M' ],}  # 19 layers
  batch_norm: False
  num_classes: 12
  # ResNet50
#  block: Bottleneck
#  layers: [3, 4, 6, 3]
#  num_classes: 12

train:
  max_epoch: 100
  batch_size: 64
  lr: 1e-3
  num_workers: 6
  optimizer:
    # type: 'adamw' # sgd / 'adamw'
    # beta1: 0.9
    # beta2: 0.999

    type: 'sgd'
    momentum: 0.99
    weight_decay: 1e-4
  schedule:
    type: 'Cosine' # Cosine / None / MultiStep
    minlr: 0
    period: 20
    warmup: 'linear'
    warmup_iters: 1 # 1 epoch
    warmup_ratio: 1e-4

    # type: 'MultiStep' # Cosine / None / MultiStep
    # milestones: [5, 10]
    # gamma: 0.5